import {
  Activity,
  Baby,
  Bone,
  Brain,
  Eye,
  Hand,
  Heart,
  LucideIcon,
  Pill,
  Radiation,
  Stethoscope,
  Syringe,
  TestTube,
  ThermometerSun,
} from "lucide-react";

import { MedicalSpecialty } from ".";

export const specialtyToIcon: Record<MedicalSpecialty, LucideIcon> = {
  [MedicalSpecialty.ALERGOLOGIA]: ThermometerSun,
  [MedicalSpecialty.ANESTESIOLOGIA]: Syringe,
  [MedicalSpecialty.ANGIOLOGIA]: Heart,
  [MedicalSpecialty.CANCEROLOGIA]: TestTube,
  [MedicalSpecialty.CARDIOLOGIA]: Heart,
  [MedicalSpecialty.CIRURGIA_CARDIOVASCULAR]: Heart,
  [MedicalSpecialty.CIRURGIA_CABECA_PESCOCO]: Stethoscope,
  [MedicalSpecialty.CIRURGIA_DIGESTIVA]: Stethoscope,
  [MedicalSpecialty.CIRURGIA_GERAL]: Stethoscope,
  [MedicalSpecialty.CIRURGIA_PEDIATRICA]: Baby,
  [MedicalSpecialty.CIRURGIA_PLASTICA]: Hand,
  [MedicalSpecialty.CIRURGIA_TORACICA]: Stethoscope,
  [MedicalSpecialty.CIRURGIA_VASCULAR]: Heart,
  [MedicalSpecialty.CLINICA_MEDICA]: Stethoscope,
  [MedicalSpecialty.DERMATOLOGIA]: Hand,
  [MedicalSpecialty.ENDOCRINOLOGIA]: Activity,
  [MedicalSpecialty.ENDOSCOPIA]: Stethoscope,
  [MedicalSpecialty.GASTROENTEROLOGIA]: Stethoscope,
  [MedicalSpecialty.GERIATRIA]: Activity,
  [MedicalSpecialty.GINECOLOGIA_OBSTETRICIA]: Baby,
  [MedicalSpecialty.HEMATOLOGIA]: TestTube,
  [MedicalSpecialty.HEPATOLOGIA]: Stethoscope,
  [MedicalSpecialty.HOMEOPATIA]: Pill,
  [MedicalSpecialty.INFECTOLOGIA]: Radiation,
  [MedicalSpecialty.MASTOLOGIA]: Stethoscope,
  [MedicalSpecialty.MEDICINA_DE_EMERGENCIA]: Activity,
  [MedicalSpecialty.MEDICINA_DO_ESPORTO]: Activity,
  [MedicalSpecialty.MEDICINA_DO_TRABALHO]: Stethoscope,
  [MedicalSpecialty.MEDICINA_DE_FAMILIA]: Stethoscope,
  [MedicalSpecialty.MEDICINA_FISICA_REABILITACAO]: Activity,
  [MedicalSpecialty.MEDICINA_INTENSIVA]: Activity,
  [MedicalSpecialty.MEDICINA_LEGAL]: Stethoscope,
  [MedicalSpecialty.NEFROLOGIA]: Stethoscope,
  [MedicalSpecialty.NEUROCIRURGIA]: Brain,
  [MedicalSpecialty.NEUROLOGIA]: Brain,
  [MedicalSpecialty.NUTROLOGIA]: Stethoscope,
  [MedicalSpecialty.OFTALMOLOGIA]: Eye,
  [MedicalSpecialty.ONCOLOGIA_CLINICA]: TestTube,
  [MedicalSpecialty.ORTOPEDIA_TRAUMATOLOGIA]: Bone,
  [MedicalSpecialty.OTORRINOLARINGOLOGIA]: Stethoscope,
  [MedicalSpecialty.PATOLOGIA]: TestTube,
  [MedicalSpecialty.PATOLOGIA_CLINICA]: TestTube,
  [MedicalSpecialty.PEDIATRIA]: Baby,
  [MedicalSpecialty.PNEUMOLOGIA]: Stethoscope,
  [MedicalSpecialty.PSIQUIATRIA]: Brain,
  [MedicalSpecialty.RADIOLOGIA]: Stethoscope,
  [MedicalSpecialty.RADIOTERAPIA]: Stethoscope,
  [MedicalSpecialty.REUMATOLOGIA]: Bone,
  [MedicalSpecialty.UROLOGIA]: Stethoscope,
};
